import Head from 'next/head'
import Image from 'next/image'
import Table from '../components/table';
import style from '../styles/Home.module.scss';
import { BsFillPersonPlusFill } from "react-icons/bs";
import Leafs from '../components/Leafs';
import Form from '../components/Forms/Form';
import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { changeForm, deleteAction } from '../redux/reducers';
import { useMutation, useQueryClient } from 'react-query';
import { deleteUserDetails, getUser, getUserDetails } from '../controllers/helper';

export default function Home() {
  const dispatch = useDispatch()
  const queryClient = useQueryClient()
  const visible = useSelector((state) => state.app.client.toggleForm)
  const deleteId = useSelector((state) => state.app.client.deleteId)
  const deleteMutation = useMutation((deleteId) => deleteUserDetails(deleteId), {
    onSuccess: () => {
      dispatch(deleteAction(null))
      queryClient.prefetchQuery('users', getUserDetails)

    }
  })
  const chForm = () => {
    dispatch(changeForm())
  }
  const deleteHandler = async () => {
    await deleteMutation.mutate(deleteId)
  }
  const cancelHandler = async () => {
    await dispatch(deleteAction(null))
  }

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.container}>
        <Leafs />
        <div className={style.home}>
          <header>
            <h1>CRUD</h1>
          </header>
          <div className={style.table}>
            <div className={style.flex}>
              <div>
                <div className={style.addButton} onClick={chForm}>
                  <span>ADD</span><BsFillPersonPlusFill /> </div>
              </div>
              {deleteId ? deleteComponent({ deleteHandler, cancelHandler }) : <></>}
            </div>
            {visible ? <Form /> : <></>}
            <div>
              <Table></Table>
            </div>
          </div>
        </div>
      </main>
    </section>
  )
}

function deleteComponent({ deleteHandler, cancelHandler }) {
  return (
    <div className={style.delete}>
      <p>Are you sure want to delete ?</p>
      <button className={style.yes} onClick={deleteHandler}>Yes</button>
      <button className={style.no} onClick={cancelHandler}>No</button>
    </div>
  )
}
